import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import '../../../core/constants/firestore_constants.dart';
import '../models/class_model.dart';
import '../../auth/models/user_model.dart';

class ClassroomService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Generate a random 6-character code
  String _generateJoinCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rnd = Random();
    return String.fromCharCodes(Iterable.generate(
        6, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));
  }

  // Academic: Create a new class
  Future<void> createClass({
    required String className,
    required String teacherId,
    required String teacherName,
  }) async {
    try {
      final joinCode = _generateJoinCode();
      final newClass = ClassModel(
        id: '', // Generated by Firestore
        className: className,
        teacherId: teacherId,
        teacherName: teacherName,
        joinCode: joinCode,
        createdAt: DateTime.now(),
      );

      // We use toMap but need to exclude ID and handle server timestamp manually if needed
      // Or just use the map directly as before but safer key names if valid
      await _firestore.collection(FirestoreConstants.classesCollection).add({
        ...newClass.toMap(),
        'createdAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('Error creating class: $e');
      rethrow;
    }
  }

  // Student: Join a class by joinCode
  Future<void> joinClass({
    required String joinCode,
    required String studentId,
  }) async {
    try {
      final querySnapshot = await _firestore
          .collection(FirestoreConstants.classesCollection)
          .where('joinCode', isEqualTo: joinCode)
          .limit(1)
          .get();

      if (querySnapshot.docs.isEmpty) {
        throw Exception("Geçersiz ders kodu! Lütfen kontrol edin.");
      }

      final doc = querySnapshot.docs.first;
      final classModel = ClassModel.fromMap(doc.data(), doc.id);
      
      if (classModel.studentIds.contains(studentId)) {
        throw Exception("Zaten bu derse kayıtlısınız.");
      }

      await doc.reference.update({
        'studentIds': FieldValue.arrayUnion([studentId])
      });
    } catch (e) {
      debugPrint('Error joining class: $e');
      rethrow;
    }
  }

  // Get classes based on user role
  Stream<List<ClassModel>> getUserClasses(String userId, String role) {
    if (role == 'academician') {
      return _firestore
          .collection(FirestoreConstants.classesCollection)
          .where('teacherId', isEqualTo: userId)
          .orderBy('createdAt', descending: true)
          .snapshots()
          .map((snapshot) => snapshot.docs
              .map((doc) => ClassModel.fromMap(doc.data(), doc.id))
              .toList());
    } else {
      return _firestore
          .collection(FirestoreConstants.classesCollection)
          .where('studentIds', arrayContains: userId)
          .snapshots()
          .map((snapshot) => snapshot.docs
              .map((doc) => ClassModel.fromMap(doc.data(), doc.id))
              .toList());
    }
  }

  // --- ANNOUNCEMENTS ---

  Stream<QuerySnapshot> getAnnouncements(String classId) {
    return _firestore
        .collection(FirestoreConstants.classesCollection)
        .doc(classId)
        .collection(FirestoreConstants.announcementsCollection)
        .orderBy('createdAt', descending: true)
        .snapshots();
  }

  Future<void> createAnnouncement({
    required String classId,
    required String title,
    required String content,
    required String teacherId,
  }) async {
    await _firestore
        .collection(FirestoreConstants.classesCollection)
        .doc(classId)
        .collection(FirestoreConstants.announcementsCollection)
        .add({
      'title': title,
      'content': content,
      'teacherId': teacherId,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> deleteAnnouncement(String classId, String announcementId) async {
    await _firestore
        .collection(FirestoreConstants.classesCollection)
        .doc(classId)
        .collection(FirestoreConstants.announcementsCollection)
        .doc(announcementId)
        .delete();
  }

  // --- STUDENTS ---

  // Fetch full user details for students in a class
  Future<List<UserModel>> getClassStudents(String classId) async {
    try {
      final classDoc = await _firestore.collection(FirestoreConstants.classesCollection).doc(classId).get();
      if (!classDoc.exists) return [];

      final classData = ClassModel.fromMap(classDoc.data()!, classDoc.id);
      if (classData.studentIds.isEmpty) return [];

      List<UserModel> students = [];
      
      // Batching by 10
      for (var i = 0; i < classData.studentIds.length; i += 10) {
        final end = (i + 10 < classData.studentIds.length) ? i + 10 : classData.studentIds.length;
        final batch = classData.studentIds.sublist(i, end);
        
        final query = await _firestore
            .collection(FirestoreConstants.usersCollection)
            .where(FieldPath.documentId, whereIn: batch)
            .get();
            
        for (var doc in query.docs) {
          students.add(UserModel.fromMap(doc.data(), doc.id));
        }
      }
      
      return students;
    } catch (e) {
      debugPrint("Error fetching students: $e");
      return [];
    }
  }

  // Update class name
  Future<void> updateClassName(String classId, String newName) async {
    await _firestore.collection(FirestoreConstants.classesCollection).doc(classId).update({
      'className': newName,
    });
  }

  // Delete class
  Future<void> deleteClass(String classId) async {
    await _firestore.collection(FirestoreConstants.classesCollection).doc(classId).delete();
  }

  // Leave class (for students)
  Future<void> leaveClass(String classId, String studentId) async {
    await _firestore.collection(FirestoreConstants.classesCollection).doc(classId).update({
      'studentIds': FieldValue.arrayRemove([studentId]),
    });
  }

  // Stream version of class document to watch for studentId changes
  Stream<ClassModel?> getClassStream(String classId) {
    return _firestore.collection(FirestoreConstants.classesCollection).doc(classId).snapshots().map((doc) {
      if (doc.exists && doc.data() != null) {
        return ClassModel.fromMap(doc.data() as Map<String, dynamic>, doc.id);
      }
      return null;
    });
  }
}

